### PR TITLE
Fix: Simplify autoloading

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] simplifies autoloading

Also see #62.

### CODE REVIEW

**Comment by staabm** [comment]
Seems to be a BC break?

**Comment by staabm** [comment]
A app might expect/rely pn the fact that it can include a existing bootstrap.php file

**Comment by localheinz** [comment]
@staabm 

> A app might expect/rely pn the fact that it can include a existing bootstrap.php file

A bit sad, but a good point!

**Comment by staabm** [comment]
so you leave the bootstrap.php as is and add a deprecation comment on the top of it.

**Comment by rybakit** [comment]
> so you leave the bootstrap.php as is and add a deprecation comment on the top of it.

But then you have to change `require` to `require_once` (or even remove all file inclusions), otherwise the files will be included twice?

**Comment by jvasseur** [comment]
Since master is supposed to be released as `2.0`, doing BC breaks in it is fine.

**Comment by localheinz** [comment]
@jvasseur 

Sounds good, reverting the change, then!

**Comment by nikic** [comment]
Manually applied in https://github.com/nikic/iter/commit/33c2b7c15f37307d75a4325db7b5f8d837585a6c. And yes, as this is for master only, I think it's fine to just drop the bootstrap.php file.

**Pull request closed without merging**
